apiVersion: nap.nupi.ai/v1alpha1
kind: Plugin
type: adapter
metadata:
  name: Nupi Whisper Local STT
  catalog: ai.nupi
  slug: stt-local-whisper
  description: Local speech-to-text adapter backed by Whisper.
  version: 1.0.0
spec:
  slot: stt
  homepage: https://github.com/nupi-ai/plugin-stt-local-whisper
  compatibility:
    nupi: ">=0.0.0-dev"
  entrypoint:
    command: ./stt-local-whisper
    args: []
    transport: process
    listenEnv: NUPI_ADAPTER_LISTEN_ADDR
    readyTimeout: 30s
  options:
    model_variant:
      type: enum
      default: base
      values: [tiny, base, small, medium, large]
      description: Selects the Whisper model size.
    language:
      type: string
      default: client
      description: >
        Language mode for transcription. "client" (default) reads the language
        from the nupi.lang.iso1 request metadata propagated by the daemon; falls
        back to auto-detect if no metadata is present. "auto" always lets Whisper
        auto-detect the language, ignoring client metadata. A specific ISO 639-1
        code (e.g. "en", "de") forces that language regardless of client metadata.
    model_path:
      type: string
      description: Optional absolute path to a GGUF model; overrides variant-based lookup.
    use_gpu:
      type: boolean
      default: true
      description: Enables GPU acceleration when available.
    flash_attention:
      type: boolean
      default: true
      description: Uses FlashAttention kernels (GPU-only).
    threads:
      type: integer
      default: 0
      description: Number of inference threads (0 = auto-detect).
    beam_size:
      type: integer
      default: 1
      description: Beam size for beam search decoding (1 = greedy sampling, >1 = beam search).
  assets:
    models:
      cacheDirEnv: NUPI_ADAPTER_DATA_DIR
  telemetry:
    stdout: true
    stderr: true
