apiVersion: nap.nupi.ai/v1alpha1
kind: Plugin
type: adapter
metadata:
  name: Nupi Whisper Local STT
  catalog: ai.nupi
  slug: stt-local-whisper
  description: Local speech-to-text adapter backed by Whisper.
  version: 0.1.0-dev
spec:
  moduleType: stt
  mode: local
  homepage: https://github.com/nupi-ai/module-nupi-whisper-local-stt
  compatibility:
    nupi: ">=0.0.0-dev"
  entrypoint:
    command: ./module-nupi-whisper-local-stt
    args: []
    transport: grpc
    listenEnv: NUPI_ADAPTER_LISTEN_ADDR
  options:
    model_variant:
      type: enum
      default: base
      values: [tiny, base, small, medium, large]
      description: Selects the Whisper model size.
    language:
      type: string
      default: auto
      description: ISO-639 language hint for decoding ("auto" for detection).
    model_path:
      type: string
      description: Optional absolute path to a GGUF model; overrides variant-based lookup.
  assets:
    models:
      cacheDirEnv: NUPI_MODULE_DATA_DIR
  telemetry:
    stdout: true
    stderr: true
